import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TanstackProvider } from "./_components/providers/tanstackProvider";
import ToastProvider from "./_components/providers/toastProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeowDocs",
  description: "Generated by Shancho",
  icons: "logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NuqsAdapter>
          <TanstackProvider>
            <ToastProvider>{children}</ToastProvider>
          </TanstackProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
