import type { Metadata } from "next";
import {Inter} from "next/font/google"
import "./globals.css";
import {NuqsAdapter} from "nuqs/adapters/next/app";
import {  TanstackProvider } from '../app/_components/providers/tanstack-provider';
import ToastProvider from "./_components/providers/toast-provider";
const inter = Inter ({subsets:["latin"],}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <NuqsAdapter>
          <TanstackProvider>
            <ToastProvider>
          {children}
          </ToastProvider>
          </TanstackProvider>
        
        </NuqsAdapter>
        
      </body>
    </html>
  );
}
